### ISSUE TITLE
[Question] What is the difference between this SDK and the one at Project Moby?

### ISSUE THREAD

**Issue by e-nikolov** [docker/go-docker#3]
The old location https://github.com/docker/docker/ currently redirects to https://github.com/moby/moby/

**Comment by cpuguy83** [comment]
This is not live yet.
Please do not use `github.com/docker/go-docker` in your import paths *ever*.
This repo will be is backing the package at `docker.io/go-docker`.
This will be the canonical package for interacting with the docker product.
