### ISSUE TITLE
Problem with go-digest library

### ISSUE THREAD

**Issue by weimingwill** [docker/go-docker#6]
Hi,

I download the package using `go get -d docker.io/go-docker`. When I use the library, I encounter this problem.
```
/go/src/docker.io/go-docker/service_create.go:128:36: cannot use dgst 
(type "github.com/opencontainers/go-digest".Digest) as type 
"github.com/docker/distribution/vendor/github.com/opencontainers/go-digest".Digest 
in argument to reference.WithDigest
```

If I use dependency management tool such as govendor, then there isn't such error. Because I want to use it inside docker, I prefer to use `go get -d docker.io/go-docker` directly.

Does anyone know how to solve it?

Thank you!

**Comment by thaJeztah** [comment]
This repository is still a work-in-progress, and should not yet be used (also see https://github.com/docker/go-docker/issues/3#issuecomment-333114399)

@tiborvass can we update the repository description, and add a notice to the README?

**Comment by dnephin** [comment]
Also, it says in the README https://github.com/docker/go-docker#dependency-management-tool-is-required that you should use a dependency management tool and not `go get`.
