### ISSUE TITLE
Upgrade to gogo/protobuf 0.5.0

### ISSUE THREAD

**Issue by t-bast** [docker/go-docker#7]
Hello,

First of all, thanks for the good work on that package ;)
I have an issue though, you are forcing a dependency on gogo/protobuf 0.4.0 so dep doesn't let me depend on another package that I want to use and that has a dependency on gogo/protobuf 0.5.0 (because some new features of 0.5.0 ar really required).
Could you be more permissive in that versioning? Like ^0.4.0 would be nice if gogo/protobuf respects non-breaking changes in minor versions. Or even removing the constraint unless you really need it.

Thanks!

**Comment by dnephin** [comment]
According to https://github.com/golang/dep#semantic-versioning

> When you specify a version without an operator, dep automatically uses the ^ operator by default.

So I believe we're already using `^0.4.0`

**Comment by t-bast** [comment]
It's strange, but dep doesn't allow that.
Maybe it's because my other dependency is using glide (not dep)...
Anyway the quick fix on my side was to add an override section in my Gopkg.toml to force 0.5.0 and that worked.
