### ISSUE TITLE
.Digest in argument to reference.WithDigest

### ISSUE THREAD

**Issue by allenwind** [docker/go-docker#8]
run this program: `go build dockerps.go`
from https://godoc.org/docker.io/go-docker
```go
package main

import (
	"context"
	"fmt"

	"docker.io/go-docker"
	"docker.io/go-docker/api/types"
)

func main() {
	cli, err := docker.NewEnvClient()
	if err != nil {
		panic(err)
	}

	containers, err := cli.ContainerList(context.Background(), types.ContainerListOptions{})
	if err != nil {
		panic(err)
	}

	for _, container := range containers {
		fmt.Printf("%s %s\n", container.ID[:10], container.Image)
	}
}
```
i got:
```sh
# docker.io/go-docker
../../gopath/src/docker.io/go-docker/service_create.go:128:36: cannot use dgst (type "github.com/opencontainers/go-digest".Digest) as type "github.com/docker/distribution/vendor/github.com/opencontainers/go-digest".Digest in argument to reference.WithDigest
```
my go version is go version go1.10 linux/amd64
docker version:
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.9.4
 Git commit:	7390fc6
 Built:	Tue Feb 27 22:17:40 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	7390fc6
  Built:	Tue Feb 27 22:16:13 2018
  OS/Arch:	linux/amd64
  Experimental:	false

**Comment by anthraxn8b** [comment]
@allenwind Why did you close it? How is it solved?

**Comment by allenwind** [comment]
@anthraxn8b the problem is vendor

**Comment by anthraxn8b** [comment]
@allenwind I finally understood the required directory structure and currently use dep. THX.
